import type { NextPage } from "next";
import Head from "next/head";
import AdminHeader from "../../shared/components/admin/adminHeader";

const AdminDashboard: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/adminIcon.jpg" />
      </Head>

      <>
        <AdminHeader />

      </>
    </div>
  );
};

export default AdminDashboard;
