import type { NextPage } from "next";
import Head from "next/head";
import AdminLayout from "../../shared/components/admin/AdminLayout";
// import AdminHeader from "../../shared/components/admin/adminHeader";
// import AdminSidebar from "../../shared/components/admin/adminSidebar";

const AdminDashboard: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/adminIcon.jpg" />
      </Head>

      {/* <div className=" bg-gray-700"> */}
      {/* <AdminHeader />
        <AdminSidebar /> */}

      <AdminLayout>

      </AdminLayout>



      {/* </div> */}
    </div>
  );
};

export default AdminDashboard;
